### ISSUE TITLE
this.filter is not a function

### ISSUE THREAD

**Issue by intermundos** [postcss/fly-postcss#11]
Hi,

I've got strange error. 

Using fly v 2.0.1, fly-esnext v 2.0.0. on win 10.
Installed fly-postcss, and even without consuming the module I get following error.

> TypeError: this.filter is not a function
    at Fly.module.exports (C:/Users/anton.st/WEBDEV/builds/fly/fly.build/node_modules/fly-postcss/index.js:4:10)
    at new Fly (C:/Users/anton.st/WEBDEV/builds/fly/fly.build/node_modules/fly/lib/fly.js:61:8)
    at Object.<anonymous> (C:/Users/anton.st/WEBDEV/builds/fly/fly.build/node_modules/fly/lib/cli/spawn.js:35:9)
    at Generator.next (<anonymous>)

Installed in [fly-web-kit](https://github.com/lukeed/fly-kit-web), get the same error. 

Thanks in advance for help.

**Comment by intermundos** [comment]
Found the reason. 

Have used v1 of fly-postcss.
