### ISSUE TITLE
Is this project dead, because it no longer works.

### ISSUE THREAD

**Issue by Announcement** [postcss/fly-postcss#12]
Francis [~/Documents/Projects/electron-app]
$ .\node_modules\.bin\fly client
TypeError: this.filter is not a function
    at Fly.module.exports (C:/Users/Francis/Documents/Projects/electron-app/node_modules/fly-postcss/index.js:4:10)
    at new Fly (C:/Users/Francis/Documents/Projects/electron-app/node_modules/fly/lib/fly.js:61:8)
    at Object.<anonymous> (C:/Users/Francis/Documents/Projects/electron-app/node_modules/fly/lib/cli/spawn.js:35:9)
    at tryCatcher (C:/Users/Francis/Documents/Projects/electron-app/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:/Users/Francis/Documents/Projects/electron-app/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (C:/Users/Francis/Documents/Projects/electron-app/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (C:/Users/Francis/Documents/Projects/electron-app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (C:/Users/Francis/Documents/Projects/electron-app/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (C:/Users/Francis/Documents/Projects/electron-app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (C:/Users/Francis/Documents/Projects/electron-app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (C:/Users/Francis/Documents/Projects/electron-app/node_modules/bluebird/js/release/async.js:17:14)

**Comment by hzlmn** [comment]
@Announcement It's not maintained if you want to use `postcss` you can use it directly. 
Here is simple example
```js
const postcss = require('postcss')

const x = module.exports

const BASE_DIR = 'source'
const basename = 'dist'

// Initialize processor
const processor = postcss([
  require('precss'),
  require('autoprefixer'),
])

// Process styles with postcss
x.styles = function* (task, utils) {
  yield task.source(`${BASE_DIR}/main.css`)
    .run({
      every: true,
      *func(file) {
        const result = yield processor.process(file.data.toString(), {})
        file.data = new Buffer(result.css)
        task.$.log('PostCSS finished')
      }
    })
    .rename({
      basename
    })
    .target(BASE_DIR)
}

```

Also I strongly encourage you to make a switch to [`taskr`](https://github.com/lukeed/taskr), that is evolving backward compatible version of `fly`, due to inactivity of some individuals in `fly` org.

**Comment by hzlmn** [comment]
Feel free to ping me if it not works for you.

**Comment by shinnn** [comment]
As Fly is renamed to [Taskr](https://github.com/lukeed/taskr), there is no need for us to maintain `fly-postcss` and promote it in [PostCSS](https://github.com/postcss) organization.

Thanks for starting up this project, @morishitter. Can you transfer this repository back to your personal GitHub account?

**Comment by msaktype** [comment]
@shinnn Thank you for your support. I think, I have no authority to transfer this repository from postcss organization. 🤔

**Comment by shinnn** [comment]
OK, I found the cause;

1. Transferring a repository form an organization to a personal account can be performed only by the account who will receive it.
2. @morishitter's [permission level](https://help.github.com/en/articles/permission-levels-for-an-organization) in this organization is not `Owner` but `Member` that cannot perform repository transfer.
3. `2.` deadlocks `1.`.

I'm leaving this repo as is for now.
